Fix cargo error
This dependency is causing the following error:

```
    Updating git repository `https://github.com/Fantom-foundation/libconsensus-lachesis-rs`
error: failed to load source for a dependency on `lachesis-rs`

Caused by:
  Unable to update https://github.com/Fantom-foundation/libconsensus-lachesis-rs

Caused by:
  Could not find `Cargo.toml` in `/home/agustin/.cargo/git/checkouts/libconsensus-lachesis-rs-2f52d4482308ac1e/libconsensus`
```

Removing it to allow build to succeed.